###############
##
####

GPU: [0,1,2,3]

VERBOSE: True

MODEL:
#  MODE: 'centerEsti'
#  MODE: 'F35_N8'
  MODE: 'F17_26_N9'
  SESSION: 'LTEVSFSMBI'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 26
  VAL_BATCH_SIZE: 64
  NUM_EPOCHS: 500
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 1e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 5
  RESUME: True
  TRAIN_PS: 60
  VAL_PS: 60
#  TRAIN_DIR: '../Datasets/1000fps/train' # path to training data
#  VAL_DIR: '../Datasets/1000fps/test'    # path to validation data
  TRAIN_DIR: '../Datasets/video_reduced/train' # path to training data
  VAL_DIR: '../Datasets/video_reduced/test'    # path to validation data
#  TRAIN_DIR: '../Datasets/video/train' # path to training data
#  VAL_DIR: '../Datasets/video/test'    # path to validation data
#  TRAIN_DIR: '../Datasets/video_min/train' # path to training data
#  VAL_DIR: '../Datasets/video_min/test'    # path to validation data
  CENTER_MODEL_DIR: './ckpt'
  SAVE_DIR: './ckpt'     # path to save models and images
  # SAVE_IMAGES: False
