###############
##
####

GPU: [0,1,2,3]

VERBOSE: True

MODEL:
  MODE: 'centerEsti'
  SESSION: 'LTEVSFSMBI'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 60
  NUM_EPOCHS: 3000
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 20
  RESUME: False
  TRAIN_PS: 64
  VAL_PS: 64
  TRAIN_DIR: '../Datasets/video_reduced/train' # path to training data
  VAL_DIR: '../Datasets/video_reduced/test'    # path to validation data
  SAVE_DIR: './ckpt'     # path to save models and images
  # SAVE_IMAGES: False
