###############
##
####

GPU: [0,1,2,3]

VERBOSE: True

MODEL:
#  MODE: 'centerEsti'
  MODE: 'F35_N8'
#  MODE: 'F26_N9'
#  MODE: 'F17_N9'
  SESSION: 'LTEVSFSMBI'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 61
  NUM_EPOCHS: 3000
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 50
  RESUME: False
  TRAIN_PS: 64
  VAL_PS: 64
#  TRAIN_DIR: '../Datasets/1000fps/train' # path to training data
#  VAL_DIR: '../Datasets/1000fps/test'    # path to validation data
#  TRAIN_DIR: '../Datasets/video_reduced/train' # path to training data
#  VAL_DIR: '../Datasets/video_reduced/test'    # path to validation data
#  TRAIN_DIR: '../Datasets/video/train' # path to training data
#  VAL_DIR: '../Datasets/video/test'    # path to validation data
  TRAIN_DIR: '../Datasets/video_min/train' # path to training data
  VAL_DIR: '../Datasets/video_min/test'    # path to validation data
  CENTER_MODEL_DIR: './ckpt_test'
  SAVE_DIR: './ckpt_test'     # path to save models and images
  # SAVE_IMAGES: False
