#
# Statistical machine learning lab exam.
#
# Instructions:
#
#  - do not edit this file before "BEGIN_SOLUTION" or after "END_SOLUTION"
#  - do not import any modules or external code
#
# You will get zero marks for this part if you break these rules.
#

import numpy as np


def linear_least_squares(x, y):

    ################################################
    #
    # INPUTS:
    #    x: input data, shape d by n
    #   y: output targets, shape n by 1
    #
    #  OUTPUTS:
    #   w: linear least squares weights, d by 1
    #
    ################################################

    # BEGIN_SOLUTION 
    print("x:", x.shape, x)
    print("y:", y.shape, y)
    # END_SOLUTION
    t1 = x.T@x
    print("t1:", t1, t1.shape)
    t2 = np.linalg.inv(t1)
    print("t2:", t2, t2.shape)	
    t3 = t2@x.T
    print("t3:", t3, t3.shape)	
    w = t3.T@y
    print("w:", w, w.shape)	

    # w = np.linalg.inv(x@x.T)@x.T@y
    return w
